### ISSUE TITLE
When the support for Unifi 5.9.x available [Not an Issue and want to get an update] 

### ISSUE THREAD

**Issue by DannMendis** [jacobalberty/unifi-docker#152]
### Host operating system

Example: `Debian stretch` or `Open Media Vault 3`

### What tag are you using

Example: `stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

Example: `docker run --rm --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -p 10001:10001/udp -e TZ='Africa/Johannesburg' -v ~/unifi/data:/var/lib/unifi -v ~/unifi/logs:/var/log/unifi --name unifi jacobalberty/unifi:unifi5`

Note: A screenshot of your configuration page if using a gui is acceptable

**Comment by jacobalberty** [comment]
I tried to push 5.9.29-sc a day ago, apparently there was some issue with the build, investigating now.

**Comment by jacobalberty** [comment]
Looks like it was just a docker hub random bug 
I'm rebuilding now, should be done in about 5 minutes, jacobalberty/unifi:5.9.29-sc will be available then if you want to try the stable candidate. Since they're doing a new release it may take me a few days after the official release to figure out how they're doing the new tags, for the major releases I usually try to let them lead so I can figure out how they're going to change the debian repo layout and then mimic that on the docker tags.

**Comment by billimek** [comment]
@jacobalberty I just upgraded to `jacobalberty/unifi:5.9.29-sc-8bfd7613` and seeing issues like,

```
[2018-09-29 01:08:42,994] <db-server> ERROR system - [exec] error, rc=100, cmdline=[bin/mongod, --dbpath, /usr/lib/unifi/data/db, --port, 27117, --unixSocketPrefix, /usr/lib/unifi/run, --logappend, --logpath, /usr/lib/unifi/logs/mongod.log, --bind_ip, 127.0.0.1]
[2018-09-29 01:08:42,996] <db-server> INFO  db     - DbServer stopped
[2018-09-29 01:08:43,896] <launcher> ERROR db     - Got error while connecting to db...
java.lang.NullPointerException
        at com.ubnt.service.OoOO.W.OÒ0000(Unknown Source)
        at com.ubnt.service.OoOO.W.afterPropertiesSet(Unknown Source)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:392)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:364)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b.dbService(<generated>)
        at com.ubnt.service.AppContext.statService(Unknown Source)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b.CGLIB$statService$10(<generated>)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b$$FastClassBySpringCGLIB$$b5bdd42d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b.statService(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:392)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:364)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b.statService(<generated>)
        at com.ubnt.service.AppContext.houseKeeper(Unknown Source)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b.CGLIB$houseKeeper$18(<generated>)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b$$FastClassBySpringCGLIB$$b5bdd42d.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361)
        at com.ubnt.service.AppContext$$EnhancerBySpringCGLIB$$936ec10b.houseKeeper(<generated>)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1247)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1096)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:535)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:88)
        at com.ubnt.service.B.Oo0000(Unknown Source)
        at com.ubnt.service.B.Õ00000(Unknown Source)
        at com.ubnt.ace.Launcher.main(Unknown Source)
```

from `server.log`

and 

```
2018-09-29T01:09:15.528+0000 I CONTROL  [main] ***** SERVER RESTARTED *****
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] MongoDB starting : pid=2894 port=27117 dbpath=/usr/lib/unifi/data/db 64-bit host=unifi-5dcb674667-v4bwl
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] db version v3.4.17
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] git version: 7c14a47868643bb691a507a92fe25541f998eca4
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] allocator: tcmalloc
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] modules: none
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] build environment:
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten]     distarch: x86_64
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten]     target_arch: x86_64
2018-09-29T01:09:15.531+0000 I CONTROL  [initandlisten] options: { net: { bindIp: "127.0.0.1", port: 27117, unixDomainSocket: { pathPrefix: "/usr/lib/unifi/run" } }, storage: { dbPath: "/usr/lib/unifi/data/db" }, systemLog: { destination: "file", logAppend: true, path: "/usr/lib/unifi/logs/mongod.log" } }
2018-09-29T01:09:15.545+0000 I STORAGE  [initandlisten] exception in initAndListen: 98 Unable to lock file: /usr/lib/unifi/data/db/mongod.lock Input/output error. Is a mongod instance already running?, terminating
2018-09-29T01:09:15.545+0000 I NETWORK  [initandlisten] shutdown: going to close listening sockets...
2018-09-29T01:09:15.545+0000 I NETWORK  [initandlisten] shutdown: going to flush diaglog...
2018-09-29T01:09:15.545+0000 I CONTROL  [initandlisten] now exiting
2018-09-29T01:09:15.545+0000 I CONTROL  [initandlisten] shutting down with code:100
```

from `mongo.log`


No idea if this is related to the new image or not, but raising here for awareness.

**Comment by DannMendis** [comment]
Much appreciated
