### ISSUE TITLE
jacobalberty / unifi-docker cannot connect to devices QNAP Container Station

### ISSUE THREAD

**Issue by kornakmf** [jacobalberty/unifi-docker#425]
### Host operating system

QNAP Container Station

### What tag are you using

Example: `latest`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

org.tuckey.web.filters.urlrewrite.UrlRewriteFilter INFO: destroy called                                                          
[2021-03-30 16:19:07,927] <docker-entrypoint> Exit signal received, shutting down                                                
[2021-03-30 16:19:26,113] <docker-entrypoint> Starting unifi controller service.                                                 
[2021-03-30 16:19:26,115] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode                                     
2021-03-30 16:19:30,060 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND                
2021-03-30 16:19:34,309 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"    

![image](https://user-images.githubusercontent.com/5470505/113023285-b5450300-9142-11eb-89b0-1c8f9c2d902c.png)

Name | Value |  
-- | -- | --
BASEDIR | /usr/lib/unifi |  
BIND_PRIV | true |  
CERT_IS_CHAIN | false |  
CERT_PRIVATE_NAME | privkey.pem |  
CERTDIR | /unifi/cert |  
CERTNAME | cert.pem |  
DATADIR | /unifi/data |  
GOSU_VERSION | 1.10 |  
LOGDIR | /unifi/log |  
ODATADIR | /var/lib/unifi |  
OLOGDIR | /var/log/unifi |  
PATH | /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin |  
RUNAS_UID0 | true |  
RUNDIR | /var/run/unifi |  
UNIFI_GID | 999 |  
UNIFI_UID | 999

![image](https://user-images.githubusercontent.com/5470505/113023758-34d2d200-9143-11eb-9155-960ffc08a261.png)

![image](https://user-images.githubusercontent.com/5470505/113023796-44eab180-9143-11eb-9a51-9042da045e2a.png)

### What do you expect to happen?
Connect to Unifi devices

### What actually happens?
After restoring a working backup of my PC based Unifi Controller, I can load the controller app from the QNAP machine, but the controller does not connect to my devices...

![image](https://user-images.githubusercontent.com/5470505/113023441-d6a5ef00-9142-11eb-807b-313d6e2cfe51.png)

**Comment by PrplHaz4** [comment]
Since you changed the IP of the controller, you will need to re-adopt your devices per the README:
https://github.com/jacobalberty/unifi-docker#ssh-adoption

**Comment by jakubmuransky** [comment]
```
[2021-04-06 17:12:40,063] <docker-entrypoint> Starting unifi controller service.
2021-04-06 17:12:40,655 main ERROR Error processing element InMemoryAppender ([Appenders: null]): CLASS_NOT_FOUND
2021-04-06 17:12:40,980 main ERROR Unable to locate appender "InMemoryAppender" for logger config "root"
Exception in thread "launcher" java.lang.IllegalStateException: Tomcat failed to start up
	at com.ubnt.net.OoOO.if(Unknown Source)
	at com.ubnt.service.ooOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.Óo0000(Unknown Source)
	at com.ubnt.ace.Launcher.main(Unknown Source)
Caused by: java.lang.RuntimeException: Web context failed to initialize
	... 3 more
```
Problem on docker after upgrade to stable-6
