### ISSUE TITLE
unifi hold on startup

### ISSUE THREAD

**Issue by ThomasAndreini** [jacobalberty/unifi-docker#464]
### Host operating system

Linux Alpine

### What tag are you using

latest , 6.2

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?

 docker create --init -p 8080:8080 -p 8443:8443 -p 3478:3478/udp -e TZ='Africa/Johannesburg' -v ~/unifi:/unifi --name unifi jacobalberty/unifi:6.2

**Hi, I've been trying to start the container for a few days but I can't go further.
when i start the container with root user i get these two messages and then it doesn't go further:**

[2021-08-17 00:12:47,944] <docker-entrypoint> Starting unifi controller service.

[2021-08-17 00:12:47,948] <docker-entrypoint> WARNING: Running UniFi in insecure (root) mode

**If instead I start the container with unifi user I get these messages:**

      
[2021-08-17 00:25:00,289] <docker-entrypoint> Starting unifi controller service.

2021-08-17 00:25:04,948 main ERROR RollingFileManager (logs/server.log) java.io.FileNotFoundException: logs/server.log (Permission denied) java.io.FileNotFoundException: logs/server.log (Permission denied)

	at java.io.FileOutputStream.open0(Native Method)

	at java.io.FileOutputStream.open(FileOutputStream.java:270)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)

	at java.io.FileOutputStream.<init>(FileOutputStream.java:133)

	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:671)

	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:641)

	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:113)

	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)

	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:205)

	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:146)

	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:62)

	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)

	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)

	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)

	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)

	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)

	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)

	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)

	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)

	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)

	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)

	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)

	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)

	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)

	at com.ubnt.service.system.J.super(Unknown Source)

	at com.ubnt.service.system.J.<clinit>(Unknown Source)

	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)

2021-08-17 00:25:04,971 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@23282c25] unable to create manager for [logs/server.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@7920ba90[pattern=logs/server.log.%i, append=true, bufferedIO=true, bufferSize=8192, policy=SizeBasedTriggeringPolicy(size=10485760), strategy=DefaultRolloverStrategy(min=1, max=3, useMax=false), advertiseURI=null, layout=[%d{ISO8601}] <%t> %-5p %-6c{1} - %m%n, filePermissions=null, fileOwner=null]] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@23282c25] unable to create manager for [logs/server.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@7920ba90[pattern=logs/server.log.%i, append=true, bufferedIO=true, bufferSize=8192, policy=SizeBasedTriggeringPolicy(size=10485760), strategy=DefaultRolloverStrategy(min=1, max=3, useMax=false), advertiseURI=null, layout=[%d{ISO8601}] <%t> %-5p %-6c{1} - %m%n, filePermissions=null, fileOwner=null]]

	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115)

	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)

	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:205)

	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:146)

	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:62)

	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)

	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)

	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)

	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)

	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)

	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)

	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)

	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)

	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)

	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)

	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)

	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)

	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)

	at com.ubnt.service.system.J.super(Unknown Source)

	at com.ubnt.service.system.J.<clinit>(Unknown Source)

	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)

2021-08-17 00:25:04,977 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender

	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:234)

	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:134)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1002)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:942)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:934)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:552)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:241)

	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:288)

	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:618)

	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:691)

	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:708)

	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)

	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)

	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)

	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)

	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:138)

	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:45)

	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:48)

	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:30)

	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:363)

	at com.ubnt.service.system.J.super(Unknown Source)

	at com.ubnt.service.system.J.<clinit>(Unknown Source)

	at com.ubnt.ace.Launcher.<clinit>(Unknown Source)

2021-08-17 00:25:06,116 main ERROR Null object returned for RollingFile in Appenders.

2021-08-17 00:25:06,196 main ERROR Unable to locate appender "server_log" for logger config "root"

**Comment by brontide** [comment]
Just got this myself.  I had to manually change the ownership of the logs/server.log to that of the user, if I removed it it would be recreated as root which fails. It appears to be a bug where it gets created as root but then can't be opened by java.
