### ISSUE TITLE
Unifi controller backups fail (manual and automatic)

### ISSUE THREAD

**Issue by jaydrogers** [jacobalberty/unifi-docker#91]
### Host operating system
Synology DSM 6.1.4-15217 Update 5

### What tag are you using
`stable`

### What complete docker command or docker-compose.yml do you use to launch the container (omitting sensitive values)?
![screen shot 2018-01-03 at 1 59 06 pm](https://user-images.githubusercontent.com/3174134/34537645-d113bdae-f08e-11e7-86af-3ec24e16e1ea.png)

### What do you expect to happen?
- When I go to `Settings > Maintenance`, I should be able to click `Download backup` and download a backup of my Unifi controller
- Automatic backups should be automatically running and saving to the backup folder

### What actually happens?
1. Automatic backups are not running (even though they are enabled)
2. A message appears that says the backup fails when I click `Download backup`
3. An error is logged in the <code>system.log</code>
<details>
  <summary>Click here to see <code>system.log</code> output when error occurs</h3></summary>
  <pre>
[2018-01-03 11:52:44,131] <webapi-63> INFO  system - [server backup] started
[2018-01-03 11:52:44,133] <webapi-63> INFO  db     - Connecting to mongodb://127.0.0.1:27117
[2018-01-03 11:52:44,170] <webapi-63> INFO  db     - Connecting to mongodb://127.0.0.1:27117
[2018-01-03 11:52:48,123] <webapi-63> ERROR system - Fail to create a backup for version '5.6.26'
[2018-01-03 11:52:48,123] <webapi-63> ERROR system - Info on backup error is...
java.lang.NullPointerException
	at com.ubnt.ace.G.super(Unknown Source)
	at com.ubnt.ace.G.super(Unknown Source)
	at com.ubnt.ace.G.super(Unknown Source)
	at com.ubnt.service.B.O0oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO.o00000(Unknown Source)
	at com.ubnt.service.B.A.o00000(Unknown Source)
	at com.ubnt.service.B.A$_OOo.o00000(Unknown Source)
	at com.ubnt.ace.api.int.o00000(Unknown Source)
	at com.ubnt.service.B.A.o00000(Unknown Source)
	at com.ubnt.ace.api.if.super(Unknown Source)
	at com.ubnt.ace.api.ApiServlet.service(Unknown Source)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at com.ubnt.ace.view.AuthFilter.doFilter(Unknown Source)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:440)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:177)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:615)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1115)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
[2018-01-03 11:52:48,124] <webapi-63> INFO  system - [server backup] end
[2018-01-03 11:52:48,124] <webapi-63> INFO  api    - [api] api.err.BackupFailed: /api/s/default/cmd/backup
</pre>
</details>

##### The error that is appearing on my screen:
<img width="400" alt="screen shot 2018-01-03 at 2 05 36 pm" src="https://user-images.githubusercontent.com/3174134/34537996-32ee75b8-f090-11e7-9f54-10333fc9b2e6.png">

### What I have already tried:
1. Restarted the container
2. Entered container with `docker exec -it` command → Switched to `unifi` user → validated that I could create and delete files in `/usr/lib/unifi/data/backup/` and `/unifi/data/backup/`
3. Changed "Backup Data Retention" to `Settings Only` and I also tried all other time frames

Any help would be greatly appreciated. Thanks for maintaining this container for the open source world!

**Comment by jaydrogers** [comment]
Upgrading to Unifi `5.6.29` fixed my issue. As of today, if you are on the `latest` branch you will need to update your image to `sc` (the Stable Candidate branch) or wait until `5.6.29` is pushed to the "latest" branch.

**Comment by jacobalberty** [comment]
`latest` should be on 5.6.29, i just didn't update the README.md for it

**Comment by jacobalberty** [comment]
Change was done in https://github.com/jacobalberty/unifi-docker/commit/82d65068e0105c3dd6683a92844e81bd7d9fe55f and looks like it did successfully build on the hub 6 days ago.
